
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    port: 8761
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  file:
    name: src/main/resources/script/prod_log.log
    clean-history-on-start: false
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO

