
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    hostname: localhost
    port: 8761
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
  cloud:
    gateway:
      loadbalancer:
        ribbon:
          enabled: false
      # discovery:
      #   locator:
      #     enabled: true
      #     lowerCaseServiceId: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "${CLIENT_HOST:http://localhost:4200}"
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: ORDER-SERVICE
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: PAYMENT-SERVICE
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
        - id: PRODUCT-SERVICE
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
        - id: SHIPPING-SERVICE
          uri: lb://shipping-service
          predicates:
            - Path=/shipping-service/**
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: FAVOURITE-SERVICE
          uri: lb://favourite-service
          predicates:
            - Path=/favourite-service/**
        - id: PROXY-CLIENT
          uri: lb://PROXY-CLIENT
          predicates:
            - Path=/app/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

