global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'productservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
    # - targets: ['host.docker.internal:8500']
    - targets: ['productservice:8500']
  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
    # - targets: ['host.docker.internal:8080']
    - targets: ['apigateway:8080']
  - job_name: 'servicediscovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
    # - targets: ['host.docker.internal:8761']
    - targets: ['servicediscovery:8761']