# server:
#   servlet:
#     context-path: /user-service

springdoc:
  api-docs:
    enabled: true
    path: '/user-service/v3/api-docs'
  swagger-ui:
    path: '/user-service/swagger-ui'
    config-url: '/user-service/v3/api-docs/swagger-config'
    url: '/user-service/v3/api-docs'
    doc-expansion: none
    disable-swagger-default-url: true

spring:
  # zipkin:
  #   base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  # cloud:
  #     config:
  #       uri: http://localhost:9296
  # bootstrap:
  #   enabled: true
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
    location: ${SPRING_CONFIG_IMPORT:optional:classpath:/config}
    # discovery:
    #   enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
  bulkhead:
    instances:
      bulkhedUserService:
        maxWaitDuration: 10ms
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    instances:
      bulkheadUserService:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
        keepAliveDuration: 20ms
  retry:
    instances:
      retryUserService:
        maxRetryAttempts: 5
        waitDuration: 10000
        retry-exceptions:
          - java.util.concurrent.TimeoutException
  ratelimiter:
    instances:
      userService:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 5000
        limitForPeriod: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
