
version: '3'
services:
  favourite-service-container:
    image: emarketshop/favourite-service:0.0.1
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://configserver:9296



