
version: '3'
services:
  favouriteservice:
    image: emarketshop/favourite-service:0.0.1
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=http://configserver:9296
      - PROJECT_VERSION=0.0.1



